# Generated by Django 3.0.2 on 2020-01-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='head_shot',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
