# Generated by Django 2.2.5 on 2019-11-27 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191127_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Level'),
        ),
    ]
