# Generated by Django 2.2.5 on 2019-11-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191127_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='department',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='level',
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Level'),
            preserve_default=False,
        ),
    ]
