# Generated by Django 2.2.5 on 2019-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191128_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourses',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
